/* The following code was generated by JFlex 1.4.3 on 24.11.14 15:26 */

package at.jku.ssw.cmm.gui.init;

import java.io.*;   
import javax.swing.text.Segment;   

import org.fife.ui.rsyntaxtextarea.*;   


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 24.11.14 15:26 from the specification file
 * <tt>src/at/jku/ssw/cmm/gui/init/CCompactTokenMaker.flex</tt>
 */
public class CCompactTokenMaker extends AbstractJFlexCTokenMaker {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int MLC = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1, 1
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\10\1\20\1\0\1\10\1\6\22\0\1\10\1\42\1\4"+
    "\1\7\1\0\1\43\1\45\1\3\2\23\1\22\1\46\1\6\1\47"+
    "\1\6\1\21\12\2\1\42\1\6\1\50\1\44\1\51\1\42\1\0"+
    "\32\1\1\23\1\5\1\23\1\42\1\1\1\0\1\26\1\24\1\13"+
    "\1\16\1\17\1\33\1\37\1\36\1\11\1\1\1\27\1\14\1\1"+
    "\1\12\1\31\1\41\1\1\1\25\1\30\1\32\1\15\1\40\1\35"+
    "\1\1\1\34\1\1\1\23\1\52\1\23\1\42\uff81\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\2\1\1\2\1\3\1\4\1\1\1\5\5\1"+
    "\1\6\2\7\1\10\7\1\7\7\1\11\1\12\1\11"+
    "\1\13\1\3\1\14\1\3\1\0\1\15\2\4\2\0"+
    "\1\1\1\16\6\1\1\17\1\20\12\1\1\21\1\22"+
    "\1\23\1\0\1\24\21\1\1\0\6\1\1\25\6\1"+
    "\1\0\10\1\1\0\2\1\1\0\1\26";

  private static int [] zzUnpackAction() {
    int [] result = new int[115];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\53\0\126\0\201\0\254\0\327\0\u0102\0\u012d"+
    "\0\u0158\0\u0183\0\u01ae\0\u01d9\0\u0204\0\u022f\0\126\0\u025a"+
    "\0\u0285\0\126\0\u02b0\0\u02db\0\u0306\0\u0331\0\u035c\0\u0387"+
    "\0\u03b2\0\126\0\u03dd\0\u0408\0\u0433\0\u045e\0\u0489\0\u04b4"+
    "\0\u04df\0\126\0\u050a\0\u0535\0\u0560\0\126\0\u058b\0\u05b6"+
    "\0\126\0\u05e1\0\u060c\0\u012d\0\u0637\0\u0662\0\201\0\u068d"+
    "\0\u06b8\0\u06e3\0\u070e\0\u0739\0\u0764\0\u078f\0\126\0\u07ba"+
    "\0\u07e5\0\u0810\0\u083b\0\u0866\0\u0891\0\u08bc\0\u08e7\0\u0912"+
    "\0\u093d\0\126\0\126\0\126\0\u0968\0\201\0\u0993\0\u09be"+
    "\0\u09e9\0\u0a14\0\u0a3f\0\u0a6a\0\u0a95\0\u0ac0\0\u0aeb\0\u0b16"+
    "\0\u0b41\0\u0b6c\0\u0b97\0\u0bc2\0\u0bed\0\u0c18\0\u0c43\0\u0c6e"+
    "\0\u0c99\0\u0cc4\0\u0cef\0\u0d1a\0\u0d45\0\u0d70\0\201\0\u0d9b"+
    "\0\u0dc6\0\u0df1\0\u0e1c\0\u0e47\0\u0e72\0\u0e9d\0\u0ec8\0\u0ef3"+
    "\0\u0f1e\0\u0f49\0\u0f74\0\u0f9f\0\u0fca\0\u0ff5\0\u1020\0\u104b"+
    "\0\u1076\0\u10a1\0\126";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[115];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\1\4\1\5\1\6\1\7\2\3\1\10\1\11"+
    "\1\12\1\4\1\13\1\14\1\4\1\15\1\16\1\17"+
    "\1\20\1\21\1\22\1\23\1\24\2\4\1\25\2\4"+
    "\1\26\1\4\1\27\2\4\1\30\1\31\1\32\2\21"+
    "\1\33\1\34\1\35\1\36\1\37\1\40\20\41\1\42"+
    "\1\41\1\43\30\41\54\0\2\4\6\0\7\4\4\0"+
    "\16\4\11\0\2\44\1\5\2\0\1\44\1\0\1\44"+
    "\1\0\7\44\4\0\16\44\11\0\3\45\1\46\1\45"+
    "\1\47\12\45\1\50\32\45\4\7\1\51\1\52\12\7"+
    "\1\53\32\7\10\0\1\54\1\55\51\0\1\11\43\0"+
    "\2\4\6\0\1\4\1\56\5\4\4\0\7\4\1\57"+
    "\6\4\12\0\2\4\6\0\7\4\4\0\2\4\1\60"+
    "\2\4\1\61\4\4\1\62\3\4\12\0\2\4\6\0"+
    "\1\63\5\4\1\64\4\0\16\4\12\0\2\4\6\0"+
    "\6\4\1\65\4\0\5\4\1\57\10\4\12\0\2\4"+
    "\6\0\3\4\1\60\3\4\4\0\16\4\32\0\1\66"+
    "\1\67\21\0\1\32\52\0\1\32\7\0\2\4\6\0"+
    "\7\4\4\0\1\4\1\70\3\4\1\71\10\4\12\0"+
    "\2\4\6\0\6\4\1\72\4\0\16\4\12\0\2\4"+
    "\6\0\7\4\4\0\6\4\1\73\2\4\1\74\4\4"+
    "\12\0\2\4\6\0\3\4\1\75\3\4\4\0\16\4"+
    "\12\0\2\4\6\0\7\4\4\0\1\4\1\76\10\4"+
    "\1\77\3\4\12\0\2\4\6\0\7\4\4\0\5\4"+
    "\1\100\10\4\12\0\2\4\6\0\7\4\4\0\1\4"+
    "\1\101\14\4\56\0\1\32\51\0\1\32\1\0\1\32"+
    "\50\0\1\32\2\0\1\32\53\0\1\21\53\0\1\21"+
    "\53\0\1\32\20\41\1\0\1\41\1\0\30\41\21\0"+
    "\1\102\31\0\3\44\2\0\1\44\1\0\1\44\1\0"+
    "\7\44\4\0\16\44\11\0\3\47\1\103\14\47\1\0"+
    "\35\47\1\46\14\47\1\0\32\47\3\0\1\103\47\0"+
    "\20\53\1\0\36\53\1\104\1\52\45\53\12\0\1\105"+
    "\41\0\2\4\6\0\7\4\4\0\6\4\1\106\7\4"+
    "\12\0\2\4\6\0\7\4\4\0\4\4\1\107\11\4"+
    "\12\0\2\4\6\0\1\4\1\110\5\4\4\0\16\4"+
    "\12\0\2\4\6\0\7\4\4\0\2\4\1\111\13\4"+
    "\12\0\2\4\6\0\7\4\4\0\1\112\15\4\12\0"+
    "\2\4\6\0\1\4\1\113\5\4\4\0\16\4\12\0"+
    "\2\4\6\0\7\4\4\0\7\4\1\114\6\4\11\0"+
    "\20\66\1\0\32\66\1\0\2\4\6\0\6\4\1\115"+
    "\4\0\16\4\12\0\2\4\6\0\7\4\4\0\5\4"+
    "\1\116\10\4\12\0\2\4\6\0\7\4\4\0\2\4"+
    "\1\117\3\4\1\120\7\4\12\0\2\4\6\0\7\4"+
    "\4\0\1\4\1\121\14\4\12\0\2\4\6\0\1\122"+
    "\6\4\4\0\16\4\12\0\2\4\6\0\7\4\4\0"+
    "\5\4\1\123\10\4\12\0\2\4\6\0\1\124\6\4"+
    "\4\0\16\4\12\0\2\4\6\0\1\125\6\4\4\0"+
    "\16\4\12\0\2\4\6\0\1\126\6\4\4\0\16\4"+
    "\12\0\2\4\6\0\1\127\6\4\4\0\16\4\24\0"+
    "\1\130\40\0\2\4\6\0\6\4\1\57\4\0\16\4"+
    "\12\0\2\4\6\0\7\4\4\0\4\4\1\131\1\4"+
    "\1\132\7\4\12\0\2\4\6\0\7\4\4\0\1\4"+
    "\1\106\14\4\12\0\2\4\6\0\7\4\4\0\1\4"+
    "\1\133\14\4\12\0\2\4\6\0\7\4\4\0\13\4"+
    "\1\134\2\4\12\0\2\4\6\0\7\4\4\0\2\4"+
    "\1\135\13\4\12\0\2\4\6\0\7\4\4\0\2\4"+
    "\1\136\13\4\12\0\2\4\6\0\3\4\1\106\3\4"+
    "\4\0\16\4\12\0\2\4\6\0\5\4\1\137\1\4"+
    "\4\0\16\4\12\0\2\4\6\0\4\4\1\140\2\4"+
    "\4\0\16\4\12\0\2\4\6\0\1\141\3\4\1\142"+
    "\2\4\4\0\16\4\12\0\2\4\6\0\7\4\4\0"+
    "\6\4\1\143\7\4\12\0\2\4\6\0\7\4\4\0"+
    "\2\4\1\56\13\4\12\0\2\4\6\0\7\4\4\0"+
    "\6\4\1\144\7\4\12\0\2\4\6\0\3\4\1\107"+
    "\3\4\4\0\16\4\12\0\2\4\6\0\5\4\1\106"+
    "\1\4\4\0\16\4\12\0\2\4\6\0\1\4\1\145"+
    "\5\4\4\0\16\4\25\0\1\146\37\0\2\4\6\0"+
    "\7\4\4\0\6\4\1\57\7\4\12\0\2\4\6\0"+
    "\1\147\6\4\4\0\16\4\12\0\2\4\6\0\7\4"+
    "\4\0\2\4\1\150\13\4\12\0\2\4\6\0\7\4"+
    "\4\0\6\4\1\151\7\4\12\0\2\4\6\0\4\4"+
    "\1\152\2\4\4\0\16\4\12\0\2\4\6\0\7\4"+
    "\4\0\3\4\1\57\12\4\12\0\2\4\6\0\7\4"+
    "\4\0\1\4\1\153\14\4\12\0\2\4\6\0\1\4"+
    "\1\154\5\4\4\0\16\4\12\0\2\4\6\0\2\4"+
    "\1\131\4\4\4\0\16\4\12\0\2\4\6\0\2\4"+
    "\1\155\4\4\4\0\16\4\12\0\2\4\6\0\6\4"+
    "\1\137\4\0\16\4\12\0\2\4\6\0\7\4\4\0"+
    "\6\4\1\156\7\4\26\0\1\157\36\0\2\4\6\0"+
    "\1\4\1\160\5\4\4\0\16\4\12\0\2\4\6\0"+
    "\7\4\4\0\1\4\1\161\14\4\12\0\2\4\6\0"+
    "\7\4\4\0\12\4\1\137\3\4\12\0\2\4\6\0"+
    "\3\4\1\131\3\4\4\0\16\4\12\0\2\4\6\0"+
    "\1\4\1\57\5\4\4\0\16\4\12\0\2\4\6\0"+
    "\7\4\4\0\13\4\1\106\2\4\12\0\2\4\6\0"+
    "\7\4\4\0\12\4\1\57\3\4\12\0\2\4\6\0"+
    "\7\4\4\0\7\4\1\137\6\4\27\0\1\162\35\0"+
    "\2\4\6\0\4\4\1\107\2\4\4\0\16\4\12\0"+
    "\2\4\6\0\7\4\4\0\10\4\1\57\5\4\30\0"+
    "\1\163\33\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4300];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\11\13\1\1\11\2\1\1\11\7\1\1\11"+
    "\7\1\1\11\3\1\1\11\1\1\1\0\1\11\2\1"+
    "\2\0\11\1\1\11\12\1\3\11\1\0\22\1\1\0"+
    "\15\1\1\0\10\1\1\0\2\1\1\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[115];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */

   /**   
    * Constructor.  This must be here because JFlex does not generate a   
    * no-parameter constructor.   
    */   
   public CCompactTokenMaker() {   
   }

   /**   
    * Adds the token specified to the current linked list of tokens.   
    *   
    * @param tokenType The token's type.   
    * @see #addToken(int, int, int)   
    */   
   private void addHyperlinkToken(int start, int end, int tokenType) {   
      int so = start + offsetShift;   
      addToken(zzBuffer, start,end, tokenType, so, true);   
   }   

   /**   
    * Adds the token specified to the current linked list of tokens.   
    *   
    * @param tokenType The token's type.   
    */   
   private void addToken(int tokenType) {   
      addToken(zzStartRead, zzMarkedPos-1, tokenType);   
   }   

   /**   
    * Adds the token specified to the current linked list of tokens.   
    *   
    * @param tokenType The token's type.   
    * @see #addHyperlinkToken(int, int, int)   
    */   
   private void addToken(int start, int end, int tokenType) {   
      int so = start + offsetShift;   
      addToken(zzBuffer, start,end, tokenType, so, false);   
   }   

   /**   
    * Adds the token specified to the current linked list of tokens.   
    *   
    * @param array The character array.   
    * @param start The starting offset in the array.   
    * @param end The ending offset in the array.   
    * @param tokenType The token's type.   
    * @param startOffset The offset in the document at which this token   
    *        occurs.   
    * @param hyperlink Whether this token is a hyperlink.   
    */   
   public void addToken(char[] array, int start, int end, int tokenType,   
                  int startOffset, boolean hyperlink) {   
      super.addToken(array, start,end, tokenType, startOffset, hyperlink);   
      zzStartRead = zzMarkedPos;   
   }   

   /**   
    * Returns the text to place at the beginning and end of a   
    * line to "comment" it in a this programming language.   
    *   
    * @return The start and end strings to add to a line to "comment"   
    *         it out.   
    */   
   public String[] getLineCommentStartAndEnd() {   
      return new String[] { "//", null };   
   }   

   /**   
    * Returns the first token in the linked list of tokens generated   
    * from <code>text</code>.  This method must be implemented by   
    * subclasses so they can correctly implement syntax highlighting.   
    *   
    * @param text The text from which to get tokens.   
    * @param initialTokenType The token type we should start with.   
    * @param startOffset The offset into the document at which   
    *        <code>text</code> starts.   
    * @return The first <code>Token</code> in a linked list representing   
    *         the syntax highlighted text.   
    */   
   public Token getTokenList(Segment text, int initialTokenType, int startOffset) {   

      resetTokenList();   
      this.offsetShift = -text.offset + startOffset;   

      // Start off in the proper state.   
      int state = Token.NULL;   
      switch (initialTokenType) {   
                  case Token.COMMENT_MULTILINE:   
            state = MLC;   
            start = text.offset;   
            break;   

         /* No documentation comments */   
         default:   
            state = Token.NULL;   
      }   

      s = text;   
      try {   
         yyreset(zzReader);   
         yybegin(state);   
         return yylex();   
      } catch (IOException ioe) {   
         ioe.printStackTrace();   
         return new TokenImpl();   
      }   

   }   

   /**   
    * Refills the input buffer.   
    *   
    * @return      <code>true</code> if EOF was reached, otherwise   
    *              <code>false</code>.   
    */   
   private boolean zzRefill() {   
      return zzCurrentPos>=s.offset+s.count;   
   }   

   /**   
    * Resets the scanner to read from a new input stream.   
    * Does not close the old reader.   
    *   
    * All internal variables are reset, the old input stream    
    * <b>cannot</b> be reused (internal buffer is discarded and lost).   
    * Lexical state is set to <tt>YY_INITIAL</tt>.   
    *   
    * @param reader   the new input stream    
    */   
   public final void yyreset(Reader reader) {   
      // 's' has been updated.   
      zzBuffer = s.array;   
      /*   
       * We replaced the line below with the two below it because zzRefill   
       * no longer "refills" the buffer (since the way we do it, it's always   
       * "full" the first time through, since it points to the segment's   
       * array).  So, we assign zzEndRead here.   
       */   
      //zzStartRead = zzEndRead = s.offset;   
      zzStartRead = s.offset;   
      zzEndRead = zzStartRead + s.count - 1;   
      zzCurrentPos = zzMarkedPos /*= zzPushbackPos*/ = s.offset;   
      zzLexicalState = YYINITIAL;   
      zzReader = reader;   
      zzAtBOL  = true;   
      zzAtEOF  = false;   
   }   



  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public CCompactTokenMaker(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public CCompactTokenMaker(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 136) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill_old() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset_old(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public org.fife.ui.rsyntaxtextarea.Token yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 22: 
          { addToken(Token.PREPROCESSOR);
          }
        case 23: break;
        case 6: 
          { addNullToken(); return firstToken;
          }
        case 24: break;
        case 18: 
          { addToken(Token.LITERAL_CHAR);
          }
        case 25: break;
        case 16: 
          { start = zzMarkedPos-2; yybegin(MLC);
          }
        case 26: break;
        case 5: 
          { addToken(Token.WHITESPACE);
          }
        case 27: break;
        case 19: 
          { addToken(Token.ERROR_STRING_DOUBLE);
          }
        case 28: break;
        case 14: 
          { addToken(Token.RESERVED_WORD);
          }
        case 29: break;
        case 8: 
          { addToken(Token.SEPARATOR);
          }
        case 30: break;
        case 1: 
          { addToken(Token.IDENTIFIER);
          }
        case 31: break;
        case 21: 
          { addToken(Token.FUNCTION);
          }
        case 32: break;
        case 3: 
          { addToken(Token.ERROR_CHAR); addNullToken(); return firstToken;
          }
        case 33: break;
        case 4: 
          { addToken(Token.ERROR_STRING_DOUBLE); addNullToken(); return firstToken;
          }
        case 34: break;
        case 20: 
          { addToken(Token.DATA_TYPE);
          }
        case 35: break;
        case 17: 
          { yybegin(YYINITIAL); addToken(start,zzStartRead+2-1, Token.COMMENT_MULTILINE);
          }
        case 36: break;
        case 12: 
          { addToken(Token.ERROR_CHAR);
          }
        case 37: break;
        case 13: 
          { addToken(Token.LITERAL_STRING_DOUBLE_QUOTE);
          }
        case 38: break;
        case 15: 
          { addToken(Token.COMMENT_EOL); addNullToken(); return firstToken;
          }
        case 39: break;
        case 11: 
          { addToken(Token.ERROR_NUMBER_FORMAT);
          }
        case 40: break;
        case 2: 
          { addToken(Token.LITERAL_NUMBER_DECIMAL_INT);
          }
        case 41: break;
        case 7: 
          { addToken(Token.OPERATOR);
          }
        case 42: break;
        case 9: 
          { 
          }
        case 43: break;
        case 10: 
          { addToken(start,zzStartRead-1, Token.COMMENT_MULTILINE); return firstToken;
          }
        case 44: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            switch (zzLexicalState) {
            case YYINITIAL: {
              addNullToken(); return firstToken;
            }
            case 116: break;
            case MLC: {
              addToken(start,zzStartRead-1, Token.COMMENT_MULTILINE); return firstToken;
            }
            case 117: break;
            default:
            return null;
            }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
